services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - products_service

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-pass}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - products_service

networks:
  products_service:
    driver: bridge

volumes:
  mongo_data: